parameters:
  visualStudioVersion: '2019'
  e2eTestsEnabled: false

jobs:
- job: windows_build_${{ parameters.visualStudioVersion }}_e2e_${{ parameters.e2eTestsEnabled }}
  displayName: 'Windows VS${{ parameters.visualStudioVersion }}'
  timeoutInMinutes: 240
  pool:
    vmImage: 'windows-${{ parameters.visualStudioVersion }}'
  variables:
    vcpkgGitCommitId: 8cfe802099de05ed9abab9a63db2524dd1fe1cae
  steps:
  - task: Cache@2
    displayName: 'Cache vcpkg'
    inputs:
      key: $(Build.SourcesDirectory)/.azure-pipelines/build-windows-vcpkg.txt | "$(vcpkgGitCommitId)" | "$(Agent.OS)" | "${{ parameters.visualStudioVersion }}"
      path: '$(Build.BinariesDirectory)/vcpkg'

  - task: run-vcpkg@0
    displayName: 'Run vcpkg'
    inputs:
      vcpkgArguments: '@$(Build.SourcesDirectory)/.azure-pipelines/build-windows-vcpkg.txt'
      vcpkgGitCommitId: $(vcpkgGitCommitId)
      vcpkgGitURL: https://github.com/microsoft/vcpkg

  - pwsh: |
      curl -L -o `
        $(Build.BinariesDirectory)/ninja.zip `
        https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-win.zip
      Expand-Archive -LiteralPath $(Build.BinariesDirectory)/ninja.zip -DestinationPath $(Build.BinariesDirectory)
    displayName: Prepare build

  - task: run-cmake@0
    displayName: 'Configure and build'
    inputs:
      cmakeListsOrSettingsJson: 'CMakeListsTxtAdvanced'
      cmakeListsTxtPath: '$(Build.SourcesDirectory)/CMakeLists.txt'
      cmakeBuildType: 'Release'
      cmakeGenerator: 'Ninja'
      cmakeAppendedArgs: -GNinja -DCMAKE_MAKE_PROGRAM=$(Build.BinariesDirectory)/ninja.exe -DCMAKE_BUILD_TYPE=Release -DTESTS_ENABLED=ON
      useVcpkgToolchainFile: true

  - pwsh: |
      ctest
      $tests_pass=$LastExitCode
      if ($tests_pass -ne 0) {
          echo "`n`n`nTests failed, rerunning with verbose output"
          ctest --rerun-failed --output-on-failure
      }
      exit $tests_pass
    workingDirectory: $(Build.ArtifactStagingDirectory)
    displayName: 'Run tests'

  - ${{ if eq(parameters.e2eTestsEnabled, true) }}:
    - pwsh: |
        curl -L -o `
          south-building-test.zip `
          https://demuc.de/colmap/datasets/south-building-test.zip
        Expand-Archive -LiteralPath south-building-test.zip -DestinationPath .
        ./src/exe/Release/colmap.exe automatic_reconstructor `
            --image_path south-building-test/images `
            --workspace_path south-building-test `
            --use_gpu 0 `
            --num_threads 1 `
            --quality low
        ./src/exe/Release/colmap.exe model_comparer `
            --input_path1 south-building-test/sparse/0 `
            --input_path2 south-building-test/expected-sparse/0 `
            --output_path .
        python ./scripts/python/expect_model_comparer_errors.py `
            --errors_csv_path errors.csv `
            --max_rotation_error 0.05 `
            --max_translation_error 0.05 `
            --max_proj_center_error 0.05 `
            --expected_num_images 6
      workingDirectory: $(Build.ArtifactStagingDirectory)
      displayName: 'Run E2E tests'
